AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Document formatting and preview API

Globals:
  Function:
    Runtime: python3.12
    Timeout: 10
    MemorySize: 256

Resources:
  DocumentProcessorFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: app.lambda_handler
      Environment:
        Variables:
          ALLOWED_ORIGIN: '*'
      Events:
        ProcessDocument:
          Type: Api
          Properties:
            Path: /documents/process
            Method: post
        Preflight:
          Type: Api
          Properties:
            Path: /documents/process
            Method: options
        DecodeJwt:
          Type: Api
          Properties:
            Path: /utilities/jwt/decode
            Method: post
        DecodeJwtPreflight:
          Type: Api
          Properties:
            Path: /utilities/jwt/decode
            Method: options
        EncodeUrlBase64:
          Type: Api
          Properties:
            Path: /utilities/base64/url/encode
            Method: post
        EncodeUrlBase64Preflight:
          Type: Api
          Properties:
            Path: /utilities/base64/url/encode
            Method: options
        DecodeUrlBase64:
          Type: Api
          Properties:
            Path: /utilities/base64/url/decode
            Method: post
        DecodeUrlBase64Preflight:
          Type: Api
          Properties:
            Path: /utilities/base64/url/decode
            Method: options
    Metadata:
      BuildMethod: python3.12